//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSC.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\afeg0010\\R&D\\MT\\Circuit Breakers\\SF - LF OFFER STRUCTURE 2013\\ADD LF Withdrawab" +
            "le")]
        public string LF123ADD
        {
            get
            {
                return ((string)(this["LF123ADD"]));
            }
            set
            {
                this["LF123ADD"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=|DataDirectory|\\MV.accdb")]
        public string LocalDB
        {
            get
            {
                return ((string)(this["LocalDB"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waeg00202\\Share\\TDO-Quality Improvement\\EMSC - TOOL\\Catalogues\\LF 123")]
        public string LF123CAT
        {
            get
            {
                return ((string)(this["LF123CAT"]));
            }
            set
            {
                this["LF123CAT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\afeg0010\\R&D\\MT\\PIX ROF\\01 BOM\\0.2 Configuration Tool")]
        public string HVXADD
        {
            get
            {
                return ((string)(this["HVXADD"]));
            }
            set
            {
                this["HVXADD"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waeg00202\\share\\TDO-Quality Improvement\\EMSC - TOOL\\C.B\\HVx\\CB")]
        public string HVXCAT
        {
            get
            {
                return ((string)(this["HVXCAT"]));
            }
            set
            {
                this["HVXCAT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\afeg0010\\R&D\\MT\\Circuit Breakers\\SF - LF OFFER STRUCTURE 2013\\ADD_SF\\SF_MCset4")]
        public string SFADD
        {
            get
            {
                return ((string)(this["SFADD"]));
            }
            set
            {
                this["SFADD"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waeg00202\\share\\TDO-Quality Improvement\\EMSC - TOOL\\C.B\\SF1,SF2")]
        public string SFCAT
        {
            get
            {
                return ((string)(this["SFCAT"]));
            }
            set
            {
                this["SFCAT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\afeg0010\\R&D\\MT\\Circuit Breakers\\SF - LF OFFER STRUCTURE 2013\\ADD LF Withdrawab" +
            "le\\SOCLE _ 01-CB LF withdrawable frontal for MCset.pdf")]
        public string LF123file
        {
            get
            {
                return ((string)(this["LF123file"]));
            }
            set
            {
                this["LF123file"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\afeg0010\\R&D\\MT\\PIX ROF\\01 BOM\\0.2 Configuration Tool\\CB Template REV5.02 _ 2 M" +
            "ay 2018.xlsx")]
        public string HVXfile
        {
            get
            {
                return ((string)(this["HVXfile"]));
            }
            set
            {
                this["HVXfile"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waeg00202\\share\\TDO-Quality Improvement\\EMSC - TOOL\\C.B\\Protection Relays")]
        public string ProtectionCAT
        {
            get
            {
                return ((string)(this["ProtectionCAT"]));
            }
            set
            {
                this["ProtectionCAT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\afeg0010\\R&D\\MT\\Circuit Breakers\\SF - LF OFFER STRUCTURE 2013\\ADD_SF\\SF_MCset4\\" +
            "SF WITHDRAWABLE FOR MCset4 IEC V02.02.xlsm")]
        public string SFfile
        {
            get
            {
                return ((string)(this["SFfile"]));
            }
            set
            {
                this["SFfile"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=\\\\waeg00202\\Share\\TDO-Quality Impro" +
            "vement\\EMSC - TOOL\\DB\\MV.accdb")]
        public string RemoteDB
        {
            get
            {
                return ((string)(this["RemoteDB"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waeg00202\\share\\TDO-Quality Improvement\\EMSC - TOOL\\DB\\MV.accdb")]
        public string Remote_file
        {
            get
            {
                return ((string)(this["Remote_file"]));
            }
            set
            {
                this["Remote_file"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waeg00202\\share\\TDO-Quality Improvement\\OUR (Optimum References)\\Current\\Ammete" +
            "r Scales & Ammeters (Karim Aly)\\standard Ammeter Scales & Ammeters.xlsx")]
        public string AmeterFile
        {
            get
            {
                return ((string)(this["AmeterFile"]));
            }
            set
            {
                this["AmeterFile"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waeg00202\\share\\TDO-Quality Improvement\\OUR (Optimum References)\\Current\\Lamps," +
            " Pushbuttons, Selector switches (Mohamed Ramadan)\\Standard Lamps , Selectors & P" +
            "B.xlsx")]
        public string LampFile
        {
            get
            {
                return ((string)(this["LampFile"]));
            }
            set
            {
                this["LampFile"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waeg00202\\share\\TDO-Quality Improvement\\EMSC - TOOL\\C.B\\Internal Lighting\\Intern" +
            "al Lighting for MV SWGRs.xlsx")]
        public string Internal_Lighting
        {
            get
            {
                return ((string)(this["Internal_Lighting"]));
            }
            set
            {
                this["Internal_Lighting"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ControlAux
        {
            get
            {
                return ((string)(this["ControlAux"]));
            }
            set
            {
                this["ControlAux"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waeg00202\\share\\TDO-Quality Improvement\\EMSC - TOOL\\DB")]
        public string UpdateLink
        {
            get
            {
                return ((string)(this["UpdateLink"]));
            }
            set
            {
                this["UpdateLink"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.01.01")]
        public string UpdateVersion
        {
            get
            {
                return ((string)(this["UpdateVersion"]));
            }
            set
            {
                this["UpdateVersion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MVRX64.msi")]
        public string UpdateFile
        {
            get
            {
                return ((string)(this["UpdateFile"]));
            }
            set
            {
                this["UpdateFile"] = value;
            }
        }
    }
}
